name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Debug
        run: |
          ls -la
          tree -a

      - name: Create .env file
        run: |
          touch backend/.env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> backend/.env
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> backend/.env

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          #linux/arm/v7,linux/arm64,
          platforms: linux/arm64/v8
          tags: ${{ secrets.DOCKER_USERNAME }}/rag-chatbot-backend:latest
          # tags: ${{ secrets.DOCKER_USERNAME }}/file-stash:${{ github.sha }}